---
apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: default
  labels:
    name: consul
spec:
  ports:
    # the port that this service should serve on
    - name: http
      port: 8500
    - name: rpc
      port: 8400
    - name: serflan
      port: 8301
    - name: serfwan
      port: 8302
    - name: server
      port: 8300
    - name: consuldns
      port: 8600
  type: NodePort
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: consul